#!/bin/bash
export $(grep -v '^#' .env | xargs)
if [ $1 == p ]; then
    docker build -t davifaustino/$IMAGE_NAME:$PROJECT_VERSION --no-cache .
else
    docker build --build-arg ENV_FILE=.env.development -t davifaustino/$IMAGE_NAME:$PROJECT_VERSION-dev --no-cache .
fi
